# Generated by Django 4.0.3 on 2022-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
